### ISSUE TITLE
Incorrect Subnet Mask In Docker Compose File

### ISSUE THREAD

**Issue by ewagmig** [Finschia/finschia#337]
## Summary of Bug
In the docker-compose.yml file, the networks setting is as below
```yml
networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
```

The subnet `192.168.10.0/16` is set incorrectly which should be a C-Class subnet of `192.168.10.0/24`.

This bug leads to the container running via the make command
> make localnet-start 

error was printed out as below:
```shell
invalid subnet 192.168.10.0/16: it should be 192.168.0.0/16
```

## Version
# git log

51c8c2ac51150773a06d65d632ca6b5586afa1bb

## Steps to Reproduce
Just use the make command 
> make localnet-start 
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
